# Generated by Django 4.1.7 on 2023-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_alter_admin_email_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('in_inventory', models.IntegerField()),
            ],
        ),
    ]
